//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZoneWeb.TimeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeService.IServiceTime")]
    public interface IServiceTime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTime/NewYourTime", ReplyAction="http://tempuri.org/IServiceTime/NewYourTimeResponse")]
        System.DateTime NewYourTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTime/NewYourTime", ReplyAction="http://tempuri.org/IServiceTime/NewYourTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> NewYourTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTimeChannel : TimeZoneWeb.TimeService.IServiceTime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTimeClient : System.ServiceModel.ClientBase<TimeZoneWeb.TimeService.IServiceTime>, TimeZoneWeb.TimeService.IServiceTime {
        
        public ServiceTimeClient() {
        }
        
        public ServiceTimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime NewYourTime() {
            return base.Channel.NewYourTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> NewYourTimeAsync() {
            return base.Channel.NewYourTimeAsync();
        }
    }
}
